#!/usr/bin/env bash
# Displays numbers from 1 - 100 using the while loop
# Display "FizzBuzz" when the number is multiple of 3 and 5.
# Display "Fizz" when the number is multiple of 3.
# Display "Buzz" when the number is a multiple of 5.

count=1
while [ $count -lt 100 ]
do        
	  if (( $count % 3 == 0 && $count % 5 == 0 ))
	  then
		  echo "Fizzbuzz"
	  elif (( $count % 3 == 0 ))
	  then
		  echo "Fizz"
	  elif (( $count % 5 == 0 ))
	  then
		  echo "Buzz"
	  else
		  echo $count
	  fi		 
     	 (( count++ ))
done
