#!/usr/bin/env bash
# Display "Best School" 10 times using a while loop.

count=0
while [ $count -lt 10 ]
do        if  [[ $count == 9 ]]
	  then
		  echo "Hi"
	  fi
	  echo "Best School"
	    (( count++ ))
done
